# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/Ui_ApprovalReportedList.ui'
#
# Created: Sat Nov 21 17:06:08 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(759, 429)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.approve_table_widget = QtGui.QTableWidget(Form)
        self.approve_table_widget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.approve_table_widget.setObjectName("approve_table_widget")
        self.approve_table_widget.setColumnCount(5)
        self.approve_table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.approve_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.approve_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.approve_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.approve_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.approve_table_widget.setHorizontalHeaderItem(4, item)
        self.gridLayout.addWidget(self.approve_table_widget, 1, 0, 1, 2)
        self.delete_table_widget = QtGui.QTableWidget(Form)
        self.delete_table_widget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.delete_table_widget.setObjectName("delete_table_widget")
        self.delete_table_widget.setColumnCount(7)
        self.delete_table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.delete_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.delete_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.delete_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.delete_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.delete_table_widget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.delete_table_widget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.delete_table_widget.setHorizontalHeaderItem(6, item)
        self.gridLayout.addWidget(self.delete_table_widget, 1, 2, 1, 2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.delete_push_button = QtGui.QPushButton(Form)
        self.delete_push_button.setObjectName("delete_push_button")
        self.gridLayout.addWidget(self.delete_push_button, 3, 3, 1, 1)
        self.approve_push_button = QtGui.QPushButton(Form)
        self.approve_push_button.setObjectName("approve_push_button")
        self.gridLayout.addWidget(self.approve_push_button, 3, 1, 1, 1)
        self.cancel_push_button = QtGui.QPushButton(Form)
        self.cancel_push_button.setObjectName("cancel_push_button")
        self.gridLayout.addWidget(self.cancel_push_button, 5, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 0, 1, 4)
        self.label = QtGui.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "P2PBooks", None, QtGui.QApplication.UnicodeUTF8))
        self.approve_table_widget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.approve_table_widget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.approve_table_widget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.approve_table_widget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.approve_table_widget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_table_widget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_table_widget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_table_widget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_table_widget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_table_widget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_table_widget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Form", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_table_widget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Form", "# of Reports", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_push_button.setText(QtGui.QApplication.translate("Form", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.approve_push_button.setText(QtGui.QApplication.translate("Form", "Approve", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_push_button.setText(QtGui.QApplication.translate("Form", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Approval List", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Reported List", None, QtGui.QApplication.UnicodeUTF8))

