# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/Ui_ApprovalReportedList.ui'
#
# Created: Sat Nov 21 14:56:16 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(650, 462)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.delete_push_button = QtGui.QPushButton(Form)
        self.delete_push_button.setObjectName("delete_push_button")
        self.gridLayout.addWidget(self.delete_push_button, 5, 3, 1, 1)
        self.approve_push_button = QtGui.QPushButton(Form)
        self.approve_push_button.setObjectName("approve_push_button")
        self.gridLayout.addWidget(self.approve_push_button, 5, 1, 1, 1)
        self.report_search_table = QtGui.QTableWidget(Form)
        self.report_search_table.setObjectName("report_search_table")
        self.report_search_table.setColumnCount(7)
        self.report_search_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.report_search_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.report_search_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.report_search_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.report_search_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.report_search_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.report_search_table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.report_search_table.setHorizontalHeaderItem(6, item)
        self.gridLayout.addWidget(self.report_search_table, 1, 2, 1, 2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 2, 1, 1)
        self.approve_search_table = QtGui.QTableWidget(Form)
        self.approve_search_table.setObjectName("approve_search_table")
        self.approve_search_table.setColumnCount(5)
        self.approve_search_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.approve_search_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.approve_search_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.approve_search_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.approve_search_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.approve_search_table.setHorizontalHeaderItem(4, item)
        self.gridLayout.addWidget(self.approve_search_table, 1, 0, 1, 2)
        self.cancel_push_button = QtGui.QPushButton(Form)
        self.cancel_push_button.setObjectName("cancel_push_button")
        self.gridLayout.addWidget(self.cancel_push_button, 8, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 7, 0, 1, 4)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 2)
        self.label = QtGui.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "P2PBooks", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_push_button.setText(QtGui.QApplication.translate("Form", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.approve_push_button.setText(QtGui.QApplication.translate("Form", "Approve", None, QtGui.QApplication.UnicodeUTF8))
        self.report_search_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.report_search_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.report_search_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.report_search_table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.report_search_table.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.report_search_table.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Form", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.report_search_table.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Form", "# of Reports", None, QtGui.QApplication.UnicodeUTF8))
        self.approve_search_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.approve_search_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.approve_search_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.approve_search_table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.approve_search_table.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_push_button.setText(QtGui.QApplication.translate("Form", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Reported List", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Approval List", None, QtGui.QApplication.UnicodeUTF8))

