# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\Ui_MainWindowVisitor.ui'
#
# Created: Sat Dec 12 13:03:58 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(906, 669)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.go_push_button = QtGui.QPushButton(self.centralwidget)
        self.go_push_button.setObjectName("go_push_button")
        self.gridLayout.addWidget(self.go_push_button, 4, 3, 1, 1)
        self.login_push_button = QtGui.QPushButton(self.centralwidget)
        self.login_push_button.setObjectName("login_push_button")
        self.gridLayout.addWidget(self.login_push_button, 0, 3, 1, 1)
        self.register_push_button = QtGui.QPushButton(self.centralwidget)
        self.register_push_button.setObjectName("register_push_button")
        self.gridLayout.addWidget(self.register_push_button, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 4)
        self.search_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.search_line_edit.setObjectName("search_line_edit")
        self.gridLayout.addWidget(self.search_line_edit, 4, 1, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.search_table_widget = QtGui.QTableWidget(self.centralwidget)
        self.search_table_widget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.search_table_widget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.search_table_widget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.search_table_widget.setObjectName("search_table_widget")
        self.search_table_widget.setColumnCount(7)
        self.search_table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.search_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.search_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.search_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.search_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.search_table_widget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.search_table_widget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.search_table_widget.setHorizontalHeaderItem(6, item)
        self.gridLayout.addWidget(self.search_table_widget, 5, 1, 1, 2)
        self.close_push_button = QtGui.QPushButton(self.centralwidget)
        self.close_push_button.setObjectName("close_push_button")
        self.gridLayout.addWidget(self.close_push_button, 5, 3, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.top_tab = QtGui.QWidget()
        self.top_tab.setObjectName("top_tab")
        self.gridLayout_2 = QtGui.QGridLayout(self.top_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.top_table_widget = QtGui.QTableWidget(self.top_tab)
        self.top_table_widget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.top_table_widget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.top_table_widget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.top_table_widget.setObjectName("top_table_widget")
        self.top_table_widget.setColumnCount(7)
        self.top_table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.top_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.top_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.top_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.top_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.top_table_widget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.top_table_widget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.top_table_widget.setHorizontalHeaderItem(6, item)
        self.gridLayout_2.addWidget(self.top_table_widget, 0, 0, 1, 1)
        self.top_checkout_push_button = QtGui.QPushButton(self.top_tab)
        self.top_checkout_push_button.setObjectName("top_checkout_push_button")
        self.gridLayout_2.addWidget(self.top_checkout_push_button, 1, 0, 1, 1)
        self.tabWidget.addTab(self.top_tab, "")
        self.kids_tab = QtGui.QWidget()
        self.kids_tab.setObjectName("kids_tab")
        self.gridLayout_5 = QtGui.QGridLayout(self.kids_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.kids_table_widget = QtGui.QTableWidget(self.kids_tab)
        self.kids_table_widget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.kids_table_widget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.kids_table_widget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.kids_table_widget.setObjectName("kids_table_widget")
        self.kids_table_widget.setColumnCount(7)
        self.kids_table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.kids_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.kids_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.kids_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.kids_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.kids_table_widget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.kids_table_widget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.kids_table_widget.setHorizontalHeaderItem(6, item)
        self.gridLayout_5.addWidget(self.kids_table_widget, 0, 0, 1, 1)
        self.kids_checkout_push_button = QtGui.QPushButton(self.kids_tab)
        self.kids_checkout_push_button.setObjectName("kids_checkout_push_button")
        self.gridLayout_5.addWidget(self.kids_checkout_push_button, 1, 0, 1, 1)
        self.tabWidget.addTab(self.kids_tab, "")
        self.adventure_tab = QtGui.QWidget()
        self.adventure_tab.setObjectName("adventure_tab")
        self.gridLayout_3 = QtGui.QGridLayout(self.adventure_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.adventure_table_widget = QtGui.QTableWidget(self.adventure_tab)
        self.adventure_table_widget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.adventure_table_widget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.adventure_table_widget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.adventure_table_widget.setObjectName("adventure_table_widget")
        self.adventure_table_widget.setColumnCount(7)
        self.adventure_table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.adventure_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.adventure_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.adventure_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.adventure_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.adventure_table_widget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.adventure_table_widget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.adventure_table_widget.setHorizontalHeaderItem(6, item)
        self.gridLayout_3.addWidget(self.adventure_table_widget, 0, 0, 1, 1)
        self.adventure_checkout_push_button = QtGui.QPushButton(self.adventure_tab)
        self.adventure_checkout_push_button.setObjectName("adventure_checkout_push_button")
        self.gridLayout_3.addWidget(self.adventure_checkout_push_button, 1, 0, 1, 1)
        self.tabWidget.addTab(self.adventure_tab, "")
        self.education_tab = QtGui.QWidget()
        self.education_tab.setObjectName("education_tab")
        self.gridLayout_4 = QtGui.QGridLayout(self.education_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.edu_table_widget = QtGui.QTableWidget(self.education_tab)
        self.edu_table_widget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.edu_table_widget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.edu_table_widget.setObjectName("edu_table_widget")
        self.edu_table_widget.setColumnCount(7)
        self.edu_table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.edu_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.edu_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.edu_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.edu_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.edu_table_widget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.edu_table_widget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.edu_table_widget.setHorizontalHeaderItem(6, item)
        self.gridLayout_4.addWidget(self.edu_table_widget, 0, 0, 1, 1)
        self.edu_checkout_push_button = QtGui.QPushButton(self.education_tab)
        self.edu_checkout_push_button.setObjectName("edu_checkout_push_button")
        self.gridLayout_4.addWidget(self.edu_checkout_push_button, 1, 0, 1, 1)
        self.tabWidget.addTab(self.education_tab, "")
        self.diy_tab = QtGui.QWidget()
        self.diy_tab.setObjectName("diy_tab")
        self.gridLayout_6 = QtGui.QGridLayout(self.diy_tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.diy_table_widget = QtGui.QTableWidget(self.diy_tab)
        self.diy_table_widget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.diy_table_widget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.diy_table_widget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.diy_table_widget.setObjectName("diy_table_widget")
        self.diy_table_widget.setColumnCount(7)
        self.diy_table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.diy_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.diy_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.diy_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.diy_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.diy_table_widget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.diy_table_widget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.diy_table_widget.setHorizontalHeaderItem(6, item)
        self.gridLayout_6.addWidget(self.diy_table_widget, 0, 0, 1, 1)
        self.diy_checkout_push_button = QtGui.QPushButton(self.diy_tab)
        self.diy_checkout_push_button.setObjectName("diy_checkout_push_button")
        self.gridLayout_6.addWidget(self.diy_checkout_push_button, 1, 0, 1, 1)
        self.tabWidget.addTab(self.diy_tab, "")
        self.romance_tab = QtGui.QWidget()
        self.romance_tab.setObjectName("romance_tab")
        self.gridLayout_7 = QtGui.QGridLayout(self.romance_tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.romance_table_widget = QtGui.QTableWidget(self.romance_tab)
        self.romance_table_widget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.romance_table_widget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.romance_table_widget.setObjectName("romance_table_widget")
        self.romance_table_widget.setColumnCount(7)
        self.romance_table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.romance_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.romance_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.romance_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.romance_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.romance_table_widget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.romance_table_widget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.romance_table_widget.setHorizontalHeaderItem(6, item)
        self.gridLayout_7.addWidget(self.romance_table_widget, 0, 0, 1, 1)
        self.romance_checkout_push_button = QtGui.QPushButton(self.romance_tab)
        self.romance_checkout_push_button.setObjectName("romance_checkout_push_button")
        self.gridLayout_7.addWidget(self.romance_checkout_push_button, 1, 0, 1, 1)
        self.tabWidget.addTab(self.romance_tab, "")
        self.comedy_tab = QtGui.QWidget()
        self.comedy_tab.setObjectName("comedy_tab")
        self.gridLayout_8 = QtGui.QGridLayout(self.comedy_tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.comedy_table_widget = QtGui.QTableWidget(self.comedy_tab)
        self.comedy_table_widget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.comedy_table_widget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.comedy_table_widget.setObjectName("comedy_table_widget")
        self.comedy_table_widget.setColumnCount(7)
        self.comedy_table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.comedy_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.comedy_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.comedy_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.comedy_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.comedy_table_widget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.comedy_table_widget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.comedy_table_widget.setHorizontalHeaderItem(6, item)
        self.gridLayout_8.addWidget(self.comedy_table_widget, 0, 0, 1, 1)
        self.comedy_checkout_push_button = QtGui.QPushButton(self.comedy_tab)
        self.comedy_checkout_push_button.setObjectName("comedy_checkout_push_button")
        self.gridLayout_8.addWidget(self.comedy_checkout_push_button, 1, 0, 1, 1)
        self.tabWidget.addTab(self.comedy_tab, "")
        self.fantasy_tab = QtGui.QWidget()
        self.fantasy_tab.setObjectName("fantasy_tab")
        self.gridLayout_9 = QtGui.QGridLayout(self.fantasy_tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.fantasy_table_widget = QtGui.QTableWidget(self.fantasy_tab)
        self.fantasy_table_widget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.fantasy_table_widget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.fantasy_table_widget.setObjectName("fantasy_table_widget")
        self.fantasy_table_widget.setColumnCount(7)
        self.fantasy_table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.fantasy_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.fantasy_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.fantasy_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.fantasy_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.fantasy_table_widget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.fantasy_table_widget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.fantasy_table_widget.setHorizontalHeaderItem(6, item)
        self.gridLayout_9.addWidget(self.fantasy_table_widget, 0, 0, 1, 1)
        self.fantasy_checkout_push_button = QtGui.QPushButton(self.fantasy_tab)
        self.fantasy_checkout_push_button.setObjectName("fantasy_checkout_push_button")
        self.gridLayout_9.addWidget(self.fantasy_checkout_push_button, 1, 0, 1, 1)
        self.tabWidget.addTab(self.fantasy_tab, "")
        self.biography_tab = QtGui.QWidget()
        self.biography_tab.setObjectName("biography_tab")
        self.gridLayout_10 = QtGui.QGridLayout(self.biography_tab)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.biography_table_widget = QtGui.QTableWidget(self.biography_tab)
        self.biography_table_widget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.biography_table_widget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.biography_table_widget.setObjectName("biography_table_widget")
        self.biography_table_widget.setColumnCount(7)
        self.biography_table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.biography_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.biography_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.biography_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.biography_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.biography_table_widget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.biography_table_widget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.biography_table_widget.setHorizontalHeaderItem(6, item)
        self.gridLayout_10.addWidget(self.biography_table_widget, 0, 0, 1, 1)
        self.biography_checkout_push_button = QtGui.QPushButton(self.biography_tab)
        self.biography_checkout_push_button.setObjectName("biography_checkout_push_button")
        self.gridLayout_10.addWidget(self.biography_checkout_push_button, 1, 0, 1, 1)
        self.tabWidget.addTab(self.biography_tab, "")
        self.history_tab = QtGui.QWidget()
        self.history_tab.setObjectName("history_tab")
        self.gridLayout_11 = QtGui.QGridLayout(self.history_tab)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.history_table_widget = QtGui.QTableWidget(self.history_tab)
        self.history_table_widget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.history_table_widget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.history_table_widget.setObjectName("history_table_widget")
        self.history_table_widget.setColumnCount(7)
        self.history_table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.history_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.history_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.history_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.history_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.history_table_widget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.history_table_widget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.history_table_widget.setHorizontalHeaderItem(6, item)
        self.gridLayout_11.addWidget(self.history_table_widget, 0, 0, 1, 1)
        self.history_checkout_push_button = QtGui.QPushButton(self.history_tab)
        self.history_checkout_push_button.setObjectName("history_checkout_push_button")
        self.gridLayout_11.addWidget(self.history_checkout_push_button, 1, 0, 1, 1)
        self.tabWidget.addTab(self.history_tab, "")
        self.magazine_tabs = QtGui.QWidget()
        self.magazine_tabs.setObjectName("magazine_tabs")
        self.gridLayout_12 = QtGui.QGridLayout(self.magazine_tabs)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.magazine_table_widget = QtGui.QTableWidget(self.magazine_tabs)
        self.magazine_table_widget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.magazine_table_widget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.magazine_table_widget.setObjectName("magazine_table_widget")
        self.magazine_table_widget.setColumnCount(7)
        self.magazine_table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.magazine_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.magazine_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.magazine_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.magazine_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.magazine_table_widget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.magazine_table_widget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.magazine_table_widget.setHorizontalHeaderItem(6, item)
        self.gridLayout_12.addWidget(self.magazine_table_widget, 0, 0, 1, 1)
        self.magazine_checkout_push_button = QtGui.QPushButton(self.magazine_tabs)
        self.magazine_checkout_push_button.setObjectName("magazine_checkout_push_button")
        self.gridLayout_12.addWidget(self.magazine_checkout_push_button, 1, 0, 1, 1)
        self.tabWidget.addTab(self.magazine_tabs, "")
        self.religion_tabs = QtGui.QWidget()
        self.religion_tabs.setObjectName("religion_tabs")
        self.gridLayout_13 = QtGui.QGridLayout(self.religion_tabs)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.religion_table_widget = QtGui.QTableWidget(self.religion_tabs)
        self.religion_table_widget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.religion_table_widget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.religion_table_widget.setObjectName("religion_table_widget")
        self.religion_table_widget.setColumnCount(7)
        self.religion_table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.religion_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.religion_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.religion_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.religion_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.religion_table_widget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.religion_table_widget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.religion_table_widget.setHorizontalHeaderItem(6, item)
        self.gridLayout_13.addWidget(self.religion_table_widget, 0, 0, 1, 1)
        self.religion_checkout_push_button = QtGui.QPushButton(self.religion_tabs)
        self.religion_checkout_push_button.setObjectName("religion_checkout_push_button")
        self.gridLayout_13.addWidget(self.religion_checkout_push_button, 1, 0, 1, 1)
        self.tabWidget.addTab(self.religion_tabs, "")
        self.sports_tab = QtGui.QWidget()
        self.sports_tab.setObjectName("sports_tab")
        self.gridLayout_14 = QtGui.QGridLayout(self.sports_tab)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.sports_table_widget = QtGui.QTableWidget(self.sports_tab)
        self.sports_table_widget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.sports_table_widget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.sports_table_widget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.sports_table_widget.setObjectName("sports_table_widget")
        self.sports_table_widget.setColumnCount(7)
        self.sports_table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.sports_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.sports_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.sports_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.sports_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.sports_table_widget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.sports_table_widget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.sports_table_widget.setHorizontalHeaderItem(6, item)
        self.gridLayout_14.addWidget(self.sports_table_widget, 0, 0, 1, 1)
        self.sports_checkout_push_button = QtGui.QPushButton(self.sports_tab)
        self.sports_checkout_push_button.setObjectName("sports_checkout_push_button")
        self.gridLayout_14.addWidget(self.sports_checkout_push_button, 1, 0, 1, 1)
        self.tabWidget.addTab(self.sports_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 11, 0, 1, 4)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 6, 1, 1, 3)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setLineWidth(1)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 7, 1, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 906, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "P2PBooks", None, QtGui.QApplication.UnicodeUTF8))
        self.go_push_button.setText(QtGui.QApplication.translate("MainWindow", "Go", None, QtGui.QApplication.UnicodeUTF8))
        self.login_push_button.setText(QtGui.QApplication.translate("MainWindow", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.register_push_button.setText(QtGui.QApplication.translate("MainWindow", "Register", None, QtGui.QApplication.UnicodeUTF8))
        self.search_table_widget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.search_table_widget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.search_table_widget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.search_table_widget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.search_table_widget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.search_table_widget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.search_table_widget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Cover Image", None, QtGui.QApplication.UnicodeUTF8))
        self.close_push_button.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.top_table_widget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.top_table_widget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.top_table_widget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.top_table_widget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.top_table_widget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.top_table_widget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.top_table_widget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Cover Image", None, QtGui.QApplication.UnicodeUTF8))
        self.top_checkout_push_button.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.top_tab), QtGui.QApplication.translate("MainWindow", "TOP", None, QtGui.QApplication.UnicodeUTF8))
        self.kids_table_widget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.kids_table_widget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.kids_table_widget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.kids_table_widget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.kids_table_widget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.kids_table_widget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.kids_table_widget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Cover Image", None, QtGui.QApplication.UnicodeUTF8))
        self.kids_checkout_push_button.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.kids_tab), QtGui.QApplication.translate("MainWindow", "Kids", None, QtGui.QApplication.UnicodeUTF8))
        self.adventure_table_widget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.adventure_table_widget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.adventure_table_widget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.adventure_table_widget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.adventure_table_widget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.adventure_table_widget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.adventure_table_widget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Cover Image", None, QtGui.QApplication.UnicodeUTF8))
        self.adventure_checkout_push_button.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.adventure_tab), QtGui.QApplication.translate("MainWindow", "Adventure", None, QtGui.QApplication.UnicodeUTF8))
        self.edu_table_widget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.edu_table_widget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.edu_table_widget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.edu_table_widget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.edu_table_widget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.edu_table_widget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.edu_table_widget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Cover Image", None, QtGui.QApplication.UnicodeUTF8))
        self.edu_checkout_push_button.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.education_tab), QtGui.QApplication.translate("MainWindow", "Education", None, QtGui.QApplication.UnicodeUTF8))
        self.diy_table_widget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.diy_table_widget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.diy_table_widget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.diy_table_widget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.diy_table_widget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.diy_table_widget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.diy_table_widget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Cover Image", None, QtGui.QApplication.UnicodeUTF8))
        self.diy_checkout_push_button.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.diy_tab), QtGui.QApplication.translate("MainWindow", "DIY", None, QtGui.QApplication.UnicodeUTF8))
        self.romance_table_widget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.romance_table_widget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.romance_table_widget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.romance_table_widget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.romance_table_widget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.romance_table_widget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.romance_table_widget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Cover Image", None, QtGui.QApplication.UnicodeUTF8))
        self.romance_checkout_push_button.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.romance_tab), QtGui.QApplication.translate("MainWindow", "Romance", None, QtGui.QApplication.UnicodeUTF8))
        self.comedy_table_widget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.comedy_table_widget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.comedy_table_widget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.comedy_table_widget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.comedy_table_widget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.comedy_table_widget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.comedy_table_widget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Cover Image", None, QtGui.QApplication.UnicodeUTF8))
        self.comedy_checkout_push_button.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.comedy_tab), QtGui.QApplication.translate("MainWindow", "Comedy", None, QtGui.QApplication.UnicodeUTF8))
        self.fantasy_table_widget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.fantasy_table_widget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.fantasy_table_widget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.fantasy_table_widget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.fantasy_table_widget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.fantasy_table_widget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.fantasy_table_widget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Cover Image", None, QtGui.QApplication.UnicodeUTF8))
        self.fantasy_checkout_push_button.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fantasy_tab), QtGui.QApplication.translate("MainWindow", "Fantasy", None, QtGui.QApplication.UnicodeUTF8))
        self.biography_table_widget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.biography_table_widget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.biography_table_widget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.biography_table_widget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.biography_table_widget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.biography_table_widget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.biography_table_widget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Cover Image", None, QtGui.QApplication.UnicodeUTF8))
        self.biography_checkout_push_button.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.biography_tab), QtGui.QApplication.translate("MainWindow", "Biography", None, QtGui.QApplication.UnicodeUTF8))
        self.history_table_widget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.history_table_widget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.history_table_widget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.history_table_widget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.history_table_widget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.history_table_widget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.history_table_widget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Cover Image", None, QtGui.QApplication.UnicodeUTF8))
        self.history_checkout_push_button.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.history_tab), QtGui.QApplication.translate("MainWindow", "History", None, QtGui.QApplication.UnicodeUTF8))
        self.magazine_table_widget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.magazine_table_widget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.magazine_table_widget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.magazine_table_widget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.magazine_table_widget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.magazine_table_widget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.magazine_table_widget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Cover Image", None, QtGui.QApplication.UnicodeUTF8))
        self.magazine_checkout_push_button.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.magazine_tabs), QtGui.QApplication.translate("MainWindow", "Magazine", None, QtGui.QApplication.UnicodeUTF8))
        self.religion_table_widget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.religion_table_widget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.religion_table_widget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.religion_table_widget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.religion_table_widget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.religion_table_widget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.religion_table_widget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Cover Image", None, QtGui.QApplication.UnicodeUTF8))
        self.religion_checkout_push_button.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.religion_tabs), QtGui.QApplication.translate("MainWindow", "Religion", None, QtGui.QApplication.UnicodeUTF8))
        self.sports_table_widget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.sports_table_widget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.sports_table_widget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.sports_table_widget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.sports_table_widget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.sports_table_widget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.sports_table_widget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Cover Image", None, QtGui.QApplication.UnicodeUTF8))
        self.sports_checkout_push_button.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sports_tab), QtGui.QApplication.translate("MainWindow", "Sports", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Catalog", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

