# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\Ui_MainWindowRegistered.ui'
#
# Created: Sat Nov 21 13:50:01 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1019, 691)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.username_label = QtGui.QLabel(self.centralwidget)
        self.username_label.setObjectName("username_label")
        self.gridLayout.addWidget(self.username_label, 0, 0, 1, 1)
        self.reputation_label = QtGui.QLabel(self.centralwidget)
        self.reputation_label.setObjectName("reputation_label")
        self.gridLayout.addWidget(self.reputation_label, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.upload_push_button = QtGui.QPushButton(self.centralwidget)
        self.upload_push_button.setObjectName("upload_push_button")
        self.gridLayout.addWidget(self.upload_push_button, 0, 3, 1, 1)
        self.library_push_button = QtGui.QPushButton(self.centralwidget)
        self.library_push_button.setObjectName("library_push_button")
        self.gridLayout.addWidget(self.library_push_button, 0, 4, 1, 1)
        self.library_table_widget = QtGui.QTableWidget(self.centralwidget)
        self.library_table_widget.setObjectName("library_table_widget")
        self.library_table_widget.setColumnCount(7)
        self.library_table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.library_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.library_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.library_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.library_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.library_table_widget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.library_table_widget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.library_table_widget.setHorizontalHeaderItem(6, item)
        self.gridLayout.addWidget(self.library_table_widget, 1, 0, 1, 5)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.reading_table_widget = QtGui.QTableWidget(self.centralwidget)
        self.reading_table_widget.setColumnCount(6)
        self.reading_table_widget.setObjectName("reading_table_widget")
        self.reading_table_widget.setColumnCount(6)
        self.reading_table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.reading_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.reading_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.reading_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.reading_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.reading_table_widget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.reading_table_widget.setHorizontalHeaderItem(5, item)
        self.horizontalLayout.addWidget(self.reading_table_widget)
        self.saved_table_widget = QtGui.QTableWidget(self.centralwidget)
        self.saved_table_widget.setColumnCount(6)
        self.saved_table_widget.setObjectName("saved_table_widget")
        self.saved_table_widget.setColumnCount(6)
        self.saved_table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.saved_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.saved_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.saved_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.saved_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.saved_table_widget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.saved_table_widget.setHorizontalHeaderItem(5, item)
        self.horizontalLayout.addWidget(self.saved_table_widget)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 5)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 5, 0, 1, 1)
        self.go_push_button = QtGui.QPushButton(self.centralwidget)
        self.go_push_button.setObjectName("go_push_button")
        self.gridLayout.addWidget(self.go_push_button, 6, 4, 1, 1)
        self.search_table_widget = QtGui.QTableWidget(self.centralwidget)
        self.search_table_widget.setObjectName("search_table_widget")
        self.search_table_widget.setColumnCount(6)
        self.search_table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.search_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.search_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.search_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.search_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.search_table_widget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.search_table_widget.setHorizontalHeaderItem(5, item)
        self.gridLayout.addWidget(self.search_table_widget, 7, 0, 1, 4)
        self.close_push_button = QtGui.QPushButton(self.centralwidget)
        self.close_push_button.setObjectName("close_push_button")
        self.gridLayout.addWidget(self.close_push_button, 7, 4, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 8, 0, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setLineWidth(1)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 8, 1, 1, 1)
        self.tabWidget_2 = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.top_tab_3 = QtGui.QWidget()
        self.top_tab_3.setObjectName("top_tab_3")
        self.gridLayout_28 = QtGui.QGridLayout(self.top_tab_3)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.top_table_widget_3 = QtGui.QTableWidget(self.top_tab_3)
        self.top_table_widget_3.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.top_table_widget_3.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.top_table_widget_3.setObjectName("top_table_widget_3")
        self.top_table_widget_3.setColumnCount(6)
        self.top_table_widget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.top_table_widget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.top_table_widget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.top_table_widget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.top_table_widget_3.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.top_table_widget_3.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.top_table_widget_3.setHorizontalHeaderItem(5, item)
        self.gridLayout_28.addWidget(self.top_table_widget_3, 0, 0, 1, 1)
        self.top_checkout_push_button_3 = QtGui.QPushButton(self.top_tab_3)
        self.top_checkout_push_button_3.setObjectName("top_checkout_push_button_3")
        self.gridLayout_28.addWidget(self.top_checkout_push_button_3, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.top_tab_3, "")
        self.kids_tab_3 = QtGui.QWidget()
        self.kids_tab_3.setObjectName("kids_tab_3")
        self.gridLayout_29 = QtGui.QGridLayout(self.kids_tab_3)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.kids_table_widget_3 = QtGui.QTableWidget(self.kids_tab_3)
        self.kids_table_widget_3.setObjectName("kids_table_widget_3")
        self.kids_table_widget_3.setColumnCount(6)
        self.kids_table_widget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.kids_table_widget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.kids_table_widget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.kids_table_widget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.kids_table_widget_3.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.kids_table_widget_3.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.kids_table_widget_3.setHorizontalHeaderItem(5, item)
        self.gridLayout_29.addWidget(self.kids_table_widget_3, 0, 0, 1, 1)
        self.top_checkout_push_button_4 = QtGui.QPushButton(self.kids_tab_3)
        self.top_checkout_push_button_4.setObjectName("top_checkout_push_button_4")
        self.gridLayout_29.addWidget(self.top_checkout_push_button_4, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.kids_tab_3, "")
        self.adventure_tab_3 = QtGui.QWidget()
        self.adventure_tab_3.setObjectName("adventure_tab_3")
        self.gridLayout_30 = QtGui.QGridLayout(self.adventure_tab_3)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.adventure_table_widget_3 = QtGui.QTableWidget(self.adventure_tab_3)
        self.adventure_table_widget_3.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.adventure_table_widget_3.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.adventure_table_widget_3.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.adventure_table_widget_3.setObjectName("adventure_table_widget_3")
        self.adventure_table_widget_3.setColumnCount(6)
        self.adventure_table_widget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.adventure_table_widget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.adventure_table_widget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.adventure_table_widget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.adventure_table_widget_3.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.adventure_table_widget_3.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.adventure_table_widget_3.setHorizontalHeaderItem(5, item)
        self.gridLayout_30.addWidget(self.adventure_table_widget_3, 0, 0, 1, 1)
        self.adventure_checkout_push_button_2 = QtGui.QPushButton(self.adventure_tab_3)
        self.adventure_checkout_push_button_2.setObjectName("adventure_checkout_push_button_2")
        self.gridLayout_30.addWidget(self.adventure_checkout_push_button_2, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.adventure_tab_3, "")
        self.education_tab_3 = QtGui.QWidget()
        self.education_tab_3.setObjectName("education_tab_3")
        self.gridLayout_31 = QtGui.QGridLayout(self.education_tab_3)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.edu_table_widget_3 = QtGui.QTableWidget(self.education_tab_3)
        self.edu_table_widget_3.setObjectName("edu_table_widget_3")
        self.edu_table_widget_3.setColumnCount(6)
        self.edu_table_widget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.edu_table_widget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.edu_table_widget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.edu_table_widget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.edu_table_widget_3.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.edu_table_widget_3.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.edu_table_widget_3.setHorizontalHeaderItem(5, item)
        self.gridLayout_31.addWidget(self.edu_table_widget_3, 0, 0, 1, 1)
        self.edu_checkout_push_button_2 = QtGui.QPushButton(self.education_tab_3)
        self.edu_checkout_push_button_2.setObjectName("edu_checkout_push_button_2")
        self.gridLayout_31.addWidget(self.edu_checkout_push_button_2, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.education_tab_3, "")
        self.diy_tab_3 = QtGui.QWidget()
        self.diy_tab_3.setObjectName("diy_tab_3")
        self.gridLayout_32 = QtGui.QGridLayout(self.diy_tab_3)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.diy_table_widget_3 = QtGui.QTableWidget(self.diy_tab_3)
        self.diy_table_widget_3.setObjectName("diy_table_widget_3")
        self.diy_table_widget_3.setColumnCount(6)
        self.diy_table_widget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.diy_table_widget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.diy_table_widget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.diy_table_widget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.diy_table_widget_3.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.diy_table_widget_3.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.diy_table_widget_3.setHorizontalHeaderItem(5, item)
        self.gridLayout_32.addWidget(self.diy_table_widget_3, 0, 0, 1, 1)
        self.diy_checkout_push_button_2 = QtGui.QPushButton(self.diy_tab_3)
        self.diy_checkout_push_button_2.setObjectName("diy_checkout_push_button_2")
        self.gridLayout_32.addWidget(self.diy_checkout_push_button_2, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.diy_tab_3, "")
        self.romance_tab_3 = QtGui.QWidget()
        self.romance_tab_3.setObjectName("romance_tab_3")
        self.gridLayout_33 = QtGui.QGridLayout(self.romance_tab_3)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.romance_table_widget_3 = QtGui.QTableWidget(self.romance_tab_3)
        self.romance_table_widget_3.setObjectName("romance_table_widget_3")
        self.romance_table_widget_3.setColumnCount(6)
        self.romance_table_widget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.romance_table_widget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.romance_table_widget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.romance_table_widget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.romance_table_widget_3.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.romance_table_widget_3.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.romance_table_widget_3.setHorizontalHeaderItem(5, item)
        self.gridLayout_33.addWidget(self.romance_table_widget_3, 0, 0, 1, 1)
        self.romance_checkout_push_button_2 = QtGui.QPushButton(self.romance_tab_3)
        self.romance_checkout_push_button_2.setObjectName("romance_checkout_push_button_2")
        self.gridLayout_33.addWidget(self.romance_checkout_push_button_2, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.romance_tab_3, "")
        self.comedy_tab_3 = QtGui.QWidget()
        self.comedy_tab_3.setObjectName("comedy_tab_3")
        self.gridLayout_34 = QtGui.QGridLayout(self.comedy_tab_3)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.comedy_table_widget_3 = QtGui.QTableWidget(self.comedy_tab_3)
        self.comedy_table_widget_3.setObjectName("comedy_table_widget_3")
        self.comedy_table_widget_3.setColumnCount(6)
        self.comedy_table_widget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.comedy_table_widget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.comedy_table_widget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.comedy_table_widget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.comedy_table_widget_3.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.comedy_table_widget_3.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.comedy_table_widget_3.setHorizontalHeaderItem(5, item)
        self.gridLayout_34.addWidget(self.comedy_table_widget_3, 0, 0, 1, 1)
        self.comedy_checkout_push_button_2 = QtGui.QPushButton(self.comedy_tab_3)
        self.comedy_checkout_push_button_2.setObjectName("comedy_checkout_push_button_2")
        self.gridLayout_34.addWidget(self.comedy_checkout_push_button_2, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.comedy_tab_3, "")
        self.fantasy_tab_3 = QtGui.QWidget()
        self.fantasy_tab_3.setObjectName("fantasy_tab_3")
        self.gridLayout_35 = QtGui.QGridLayout(self.fantasy_tab_3)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.fantasy_table_widget_3 = QtGui.QTableWidget(self.fantasy_tab_3)
        self.fantasy_table_widget_3.setObjectName("fantasy_table_widget_3")
        self.fantasy_table_widget_3.setColumnCount(6)
        self.fantasy_table_widget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.fantasy_table_widget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.fantasy_table_widget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.fantasy_table_widget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.fantasy_table_widget_3.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.fantasy_table_widget_3.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.fantasy_table_widget_3.setHorizontalHeaderItem(5, item)
        self.gridLayout_35.addWidget(self.fantasy_table_widget_3, 0, 0, 1, 1)
        self.fantasy_checkout_push_button_2 = QtGui.QPushButton(self.fantasy_tab_3)
        self.fantasy_checkout_push_button_2.setObjectName("fantasy_checkout_push_button_2")
        self.gridLayout_35.addWidget(self.fantasy_checkout_push_button_2, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.fantasy_tab_3, "")
        self.biography_tab_3 = QtGui.QWidget()
        self.biography_tab_3.setObjectName("biography_tab_3")
        self.gridLayout_36 = QtGui.QGridLayout(self.biography_tab_3)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.biography_table_widget_3 = QtGui.QTableWidget(self.biography_tab_3)
        self.biography_table_widget_3.setObjectName("biography_table_widget_3")
        self.biography_table_widget_3.setColumnCount(6)
        self.biography_table_widget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.biography_table_widget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.biography_table_widget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.biography_table_widget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.biography_table_widget_3.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.biography_table_widget_3.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.biography_table_widget_3.setHorizontalHeaderItem(5, item)
        self.gridLayout_36.addWidget(self.biography_table_widget_3, 0, 0, 1, 1)
        self.biography_checkout_push_button_2 = QtGui.QPushButton(self.biography_tab_3)
        self.biography_checkout_push_button_2.setObjectName("biography_checkout_push_button_2")
        self.gridLayout_36.addWidget(self.biography_checkout_push_button_2, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.biography_tab_3, "")
        self.history_tab_3 = QtGui.QWidget()
        self.history_tab_3.setObjectName("history_tab_3")
        self.gridLayout_37 = QtGui.QGridLayout(self.history_tab_3)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.history_table_widget_3 = QtGui.QTableWidget(self.history_tab_3)
        self.history_table_widget_3.setObjectName("history_table_widget_3")
        self.history_table_widget_3.setColumnCount(6)
        self.history_table_widget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.history_table_widget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.history_table_widget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.history_table_widget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.history_table_widget_3.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.history_table_widget_3.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.history_table_widget_3.setHorizontalHeaderItem(5, item)
        self.gridLayout_37.addWidget(self.history_table_widget_3, 0, 0, 1, 1)
        self.history_checkout_push_button_2 = QtGui.QPushButton(self.history_tab_3)
        self.history_checkout_push_button_2.setObjectName("history_checkout_push_button_2")
        self.gridLayout_37.addWidget(self.history_checkout_push_button_2, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.history_tab_3, "")
        self.magazine_tabs_3 = QtGui.QWidget()
        self.magazine_tabs_3.setObjectName("magazine_tabs_3")
        self.gridLayout_38 = QtGui.QGridLayout(self.magazine_tabs_3)
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.magazine_table_widget_3 = QtGui.QTableWidget(self.magazine_tabs_3)
        self.magazine_table_widget_3.setObjectName("magazine_table_widget_3")
        self.magazine_table_widget_3.setColumnCount(6)
        self.magazine_table_widget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.magazine_table_widget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.magazine_table_widget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.magazine_table_widget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.magazine_table_widget_3.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.magazine_table_widget_3.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.magazine_table_widget_3.setHorizontalHeaderItem(5, item)
        self.gridLayout_38.addWidget(self.magazine_table_widget_3, 0, 0, 1, 1)
        self.magazine_checkout_push_button_2 = QtGui.QPushButton(self.magazine_tabs_3)
        self.magazine_checkout_push_button_2.setObjectName("magazine_checkout_push_button_2")
        self.gridLayout_38.addWidget(self.magazine_checkout_push_button_2, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.magazine_tabs_3, "")
        self.religion_tabs_3 = QtGui.QWidget()
        self.religion_tabs_3.setObjectName("religion_tabs_3")
        self.gridLayout_39 = QtGui.QGridLayout(self.religion_tabs_3)
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.religion_table_widget_3 = QtGui.QTableWidget(self.religion_tabs_3)
        self.religion_table_widget_3.setObjectName("religion_table_widget_3")
        self.religion_table_widget_3.setColumnCount(6)
        self.religion_table_widget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.religion_table_widget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.religion_table_widget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.religion_table_widget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.religion_table_widget_3.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.religion_table_widget_3.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.religion_table_widget_3.setHorizontalHeaderItem(5, item)
        self.gridLayout_39.addWidget(self.religion_table_widget_3, 0, 0, 1, 1)
        self.religion_checkout_push_button_2 = QtGui.QPushButton(self.religion_tabs_3)
        self.religion_checkout_push_button_2.setObjectName("religion_checkout_push_button_2")
        self.gridLayout_39.addWidget(self.religion_checkout_push_button_2, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.religion_tabs_3, "")
        self.sports_tab_3 = QtGui.QWidget()
        self.sports_tab_3.setObjectName("sports_tab_3")
        self.gridLayout_40 = QtGui.QGridLayout(self.sports_tab_3)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.sports_table_widget_3 = QtGui.QTableWidget(self.sports_tab_3)
        self.sports_table_widget_3.setObjectName("sports_table_widget_3")
        self.sports_table_widget_3.setColumnCount(6)
        self.sports_table_widget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.sports_table_widget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.sports_table_widget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.sports_table_widget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.sports_table_widget_3.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.sports_table_widget_3.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.sports_table_widget_3.setHorizontalHeaderItem(5, item)
        self.gridLayout_40.addWidget(self.sports_table_widget_3, 0, 0, 1, 1)
        self.sports_checkout_push_button_2 = QtGui.QPushButton(self.sports_tab_3)
        self.sports_checkout_push_button_2.setObjectName("sports_checkout_push_button_2")
        self.gridLayout_40.addWidget(self.sports_checkout_push_button_2, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.sports_tab_3, "")
        self.gridLayout.addWidget(self.tabWidget_2, 9, 0, 1, 5)
        self.search_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.search_line_edit.setObjectName("search_line_edit")
        self.gridLayout.addWidget(self.search_line_edit, 6, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1019, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "P2PBooks", None, QtGui.QApplication.UnicodeUTF8))
        self.username_label.setText(QtGui.QApplication.translate("MainWindow", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.reputation_label.setText(QtGui.QApplication.translate("MainWindow", "Reputation", None, QtGui.QApplication.UnicodeUTF8))
        self.upload_push_button.setText(QtGui.QApplication.translate("MainWindow", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.library_push_button.setText(QtGui.QApplication.translate("MainWindow", "Library", None, QtGui.QApplication.UnicodeUTF8))
        self.library_table_widget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.library_table_widget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.library_table_widget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.library_table_widget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.library_table_widget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.library_table_widget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.library_table_widget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "# of Reports", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Reading", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Saved", None, QtGui.QApplication.UnicodeUTF8))
        self.reading_table_widget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.reading_table_widget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.reading_table_widget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.reading_table_widget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.reading_table_widget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.reading_table_widget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.saved_table_widget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.saved_table_widget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.saved_table_widget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.saved_table_widget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.saved_table_widget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.saved_table_widget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.go_push_button.setText(QtGui.QApplication.translate("MainWindow", "Go", None, QtGui.QApplication.UnicodeUTF8))
        self.search_table_widget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.search_table_widget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.search_table_widget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.search_table_widget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.search_table_widget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.search_table_widget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.close_push_button.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Catalog", None, QtGui.QApplication.UnicodeUTF8))
        self.top_table_widget_3.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.top_table_widget_3.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.top_table_widget_3.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.top_table_widget_3.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.top_table_widget_3.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.top_table_widget_3.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.top_checkout_push_button_3.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.top_tab_3), QtGui.QApplication.translate("MainWindow", "TOP", None, QtGui.QApplication.UnicodeUTF8))
        self.kids_table_widget_3.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.kids_table_widget_3.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.kids_table_widget_3.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.kids_table_widget_3.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.kids_table_widget_3.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.kids_table_widget_3.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.top_checkout_push_button_4.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.kids_tab_3), QtGui.QApplication.translate("MainWindow", "Kids", None, QtGui.QApplication.UnicodeUTF8))
        self.adventure_table_widget_3.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.adventure_table_widget_3.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.adventure_table_widget_3.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.adventure_table_widget_3.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.adventure_table_widget_3.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.adventure_table_widget_3.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.adventure_checkout_push_button_2.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.adventure_tab_3), QtGui.QApplication.translate("MainWindow", "Adventure", None, QtGui.QApplication.UnicodeUTF8))
        self.edu_table_widget_3.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.edu_table_widget_3.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.edu_table_widget_3.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.edu_table_widget_3.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.edu_table_widget_3.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.edu_table_widget_3.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.edu_checkout_push_button_2.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.education_tab_3), QtGui.QApplication.translate("MainWindow", "Education", None, QtGui.QApplication.UnicodeUTF8))
        self.diy_table_widget_3.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.diy_table_widget_3.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.diy_table_widget_3.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.diy_table_widget_3.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.diy_table_widget_3.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.diy_table_widget_3.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.diy_checkout_push_button_2.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.diy_tab_3), QtGui.QApplication.translate("MainWindow", "DIY", None, QtGui.QApplication.UnicodeUTF8))
        self.romance_table_widget_3.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.romance_table_widget_3.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.romance_table_widget_3.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.romance_table_widget_3.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.romance_table_widget_3.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.romance_table_widget_3.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.romance_checkout_push_button_2.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.romance_tab_3), QtGui.QApplication.translate("MainWindow", "Romance", None, QtGui.QApplication.UnicodeUTF8))
        self.comedy_table_widget_3.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.comedy_table_widget_3.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.comedy_table_widget_3.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.comedy_table_widget_3.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.comedy_table_widget_3.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.comedy_table_widget_3.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.comedy_checkout_push_button_2.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.comedy_tab_3), QtGui.QApplication.translate("MainWindow", "Comedy", None, QtGui.QApplication.UnicodeUTF8))
        self.fantasy_table_widget_3.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.fantasy_table_widget_3.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.fantasy_table_widget_3.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.fantasy_table_widget_3.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.fantasy_table_widget_3.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.fantasy_table_widget_3.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.fantasy_checkout_push_button_2.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.fantasy_tab_3), QtGui.QApplication.translate("MainWindow", "Fantasy", None, QtGui.QApplication.UnicodeUTF8))
        self.biography_table_widget_3.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.biography_table_widget_3.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.biography_table_widget_3.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.biography_table_widget_3.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.biography_table_widget_3.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.biography_table_widget_3.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.biography_checkout_push_button_2.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.biography_tab_3), QtGui.QApplication.translate("MainWindow", "Biography", None, QtGui.QApplication.UnicodeUTF8))
        self.history_table_widget_3.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.history_table_widget_3.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.history_table_widget_3.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.history_table_widget_3.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.history_table_widget_3.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.history_table_widget_3.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.history_checkout_push_button_2.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.history_tab_3), QtGui.QApplication.translate("MainWindow", "History", None, QtGui.QApplication.UnicodeUTF8))
        self.magazine_table_widget_3.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.magazine_table_widget_3.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.magazine_table_widget_3.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.magazine_table_widget_3.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.magazine_table_widget_3.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.magazine_table_widget_3.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.magazine_checkout_push_button_2.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.magazine_tabs_3), QtGui.QApplication.translate("MainWindow", "Magazine", None, QtGui.QApplication.UnicodeUTF8))
        self.religion_table_widget_3.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.religion_table_widget_3.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.religion_table_widget_3.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.religion_table_widget_3.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.religion_table_widget_3.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.religion_table_widget_3.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.religion_checkout_push_button_2.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.religion_tabs_3), QtGui.QApplication.translate("MainWindow", "Religion", None, QtGui.QApplication.UnicodeUTF8))
        self.sports_table_widget_3.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.sports_table_widget_3.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.sports_table_widget_3.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.sports_table_widget_3.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.sports_table_widget_3.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.sports_table_widget_3.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.sports_checkout_push_button_2.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.sports_tab_3), QtGui.QApplication.translate("MainWindow", "Sports", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

