# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\Ui_MainWindowVisitor.ui'
#
# Created: Fri Nov 06 21:59:37 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(879, 576)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.register_push_button = QtGui.QPushButton(self.centralwidget)
        self.register_push_button.setObjectName("register_push_button")
        self.gridLayout.addWidget(self.register_push_button, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setLineWidth(1)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 3)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.search_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.search_line_edit.setObjectName("search_line_edit")
        self.gridLayout.addWidget(self.search_line_edit, 3, 1, 1, 1)
        self.login_push_button = QtGui.QPushButton(self.centralwidget)
        self.login_push_button.setObjectName("login_push_button")
        self.gridLayout.addWidget(self.login_push_button, 0, 3, 1, 1)
        self.go_push_button = QtGui.QPushButton(self.centralwidget)
        self.go_push_button.setObjectName("go_push_button")
        self.gridLayout.addWidget(self.go_push_button, 3, 2, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.top_tab = QtGui.QWidget()
        self.top_tab.setObjectName("top_tab")
        self.gridLayout_2 = QtGui.QGridLayout(self.top_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget = QtGui.QTableWidget(self.top_tab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.top_tab, "")
        self.kids_tab = QtGui.QWidget()
        self.kids_tab.setObjectName("kids_tab")
        self.gridLayout_5 = QtGui.QGridLayout(self.kids_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableWidget_4 = QtGui.QTableWidget(self.kids_tab)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(6)
        self.tableWidget_4.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        self.gridLayout_5.addWidget(self.tableWidget_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.kids_tab, "")
        self.adventure_tab = QtGui.QWidget()
        self.adventure_tab.setObjectName("adventure_tab")
        self.gridLayout_3 = QtGui.QGridLayout(self.adventure_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget_2 = QtGui.QTableWidget(self.adventure_tab)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.gridLayout_3.addWidget(self.tableWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.adventure_tab, "")
        self.education_tab = QtGui.QWidget()
        self.education_tab.setObjectName("education_tab")
        self.gridLayout_4 = QtGui.QGridLayout(self.education_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget_3 = QtGui.QTableWidget(self.education_tab)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(6)
        self.tableWidget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        self.gridLayout_4.addWidget(self.tableWidget_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.education_tab, "")
        self.diy_tab = QtGui.QWidget()
        self.diy_tab.setObjectName("diy_tab")
        self.gridLayout_6 = QtGui.QGridLayout(self.diy_tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tableWidget_5 = QtGui.QTableWidget(self.diy_tab)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(6)
        self.tableWidget_5.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(5, item)
        self.gridLayout_6.addWidget(self.tableWidget_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.diy_tab, "")
        self.romance_tab = QtGui.QWidget()
        self.romance_tab.setObjectName("romance_tab")
        self.gridLayout_7 = QtGui.QGridLayout(self.romance_tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tableWidget_6 = QtGui.QTableWidget(self.romance_tab)
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(6)
        self.tableWidget_6.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(5, item)
        self.gridLayout_7.addWidget(self.tableWidget_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.romance_tab, "")
        self.comedy_tab = QtGui.QWidget()
        self.comedy_tab.setObjectName("comedy_tab")
        self.gridLayout_8 = QtGui.QGridLayout(self.comedy_tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tableWidget_7 = QtGui.QTableWidget(self.comedy_tab)
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(6)
        self.tableWidget_7.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(5, item)
        self.gridLayout_8.addWidget(self.tableWidget_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.comedy_tab, "")
        self.fantasy_tab = QtGui.QWidget()
        self.fantasy_tab.setObjectName("fantasy_tab")
        self.gridLayout_9 = QtGui.QGridLayout(self.fantasy_tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tableWidget_8 = QtGui.QTableWidget(self.fantasy_tab)
        self.tableWidget_8.setObjectName("tableWidget_8")
        self.tableWidget_8.setColumnCount(6)
        self.tableWidget_8.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(5, item)
        self.gridLayout_9.addWidget(self.tableWidget_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.fantasy_tab, "")
        self.biography_tab = QtGui.QWidget()
        self.biography_tab.setObjectName("biography_tab")
        self.gridLayout_10 = QtGui.QGridLayout(self.biography_tab)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tableWidget_9 = QtGui.QTableWidget(self.biography_tab)
        self.tableWidget_9.setObjectName("tableWidget_9")
        self.tableWidget_9.setColumnCount(6)
        self.tableWidget_9.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(5, item)
        self.gridLayout_10.addWidget(self.tableWidget_9, 0, 0, 1, 1)
        self.tabWidget.addTab(self.biography_tab, "")
        self.history_tab = QtGui.QWidget()
        self.history_tab.setObjectName("history_tab")
        self.gridLayout_11 = QtGui.QGridLayout(self.history_tab)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.tableWidget_10 = QtGui.QTableWidget(self.history_tab)
        self.tableWidget_10.setObjectName("tableWidget_10")
        self.tableWidget_10.setColumnCount(6)
        self.tableWidget_10.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(5, item)
        self.gridLayout_11.addWidget(self.tableWidget_10, 0, 0, 1, 1)
        self.tabWidget.addTab(self.history_tab, "")
        self.magazine_tabs = QtGui.QWidget()
        self.magazine_tabs.setObjectName("magazine_tabs")
        self.gridLayout_12 = QtGui.QGridLayout(self.magazine_tabs)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.tableWidget_11 = QtGui.QTableWidget(self.magazine_tabs)
        self.tableWidget_11.setObjectName("tableWidget_11")
        self.tableWidget_11.setColumnCount(6)
        self.tableWidget_11.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_11.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_11.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_11.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_11.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_11.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_11.setHorizontalHeaderItem(5, item)
        self.gridLayout_12.addWidget(self.tableWidget_11, 0, 0, 1, 1)
        self.tabWidget.addTab(self.magazine_tabs, "")
        self.religion_tabs = QtGui.QWidget()
        self.religion_tabs.setObjectName("religion_tabs")
        self.gridLayout_13 = QtGui.QGridLayout(self.religion_tabs)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.tableWidget_12 = QtGui.QTableWidget(self.religion_tabs)
        self.tableWidget_12.setObjectName("tableWidget_12")
        self.tableWidget_12.setColumnCount(6)
        self.tableWidget_12.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(5, item)
        self.gridLayout_13.addWidget(self.tableWidget_12, 0, 0, 1, 1)
        self.tabWidget.addTab(self.religion_tabs, "")
        self.sports_tab = QtGui.QWidget()
        self.sports_tab.setObjectName("sports_tab")
        self.gridLayout_14 = QtGui.QGridLayout(self.sports_tab)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.tableWidget_13 = QtGui.QTableWidget(self.sports_tab)
        self.tableWidget_13.setObjectName("tableWidget_13")
        self.tableWidget_13.setColumnCount(6)
        self.tableWidget_13.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_13.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_13.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_13.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_13.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_13.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_13.setHorizontalHeaderItem(5, item)
        self.gridLayout_14.addWidget(self.tableWidget_13, 0, 0, 1, 1)
        self.tabWidget.addTab(self.sports_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 5, 0, 1, 4)
        self.search_table_widget = QtGui.QTableWidget(self.centralwidget)
        self.search_table_widget.setObjectName("search_table_widget")
        self.search_table_widget.setColumnCount(6)
        self.search_table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.search_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.search_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.search_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.search_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.search_table_widget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.search_table_widget.setHorizontalHeaderItem(5, item)
        self.gridLayout.addWidget(self.search_table_widget, 4, 1, 1, 2)
        self.close_push_button = QtGui.QPushButton(self.centralwidget)
        self.close_push_button.setObjectName("close_push_button")
        self.gridLayout.addWidget(self.close_push_button, 4, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 879, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "P2PBooks", None, QtGui.QApplication.UnicodeUTF8))
        self.register_push_button.setText(QtGui.QApplication.translate("MainWindow", "Register", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Catalog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.login_push_button.setText(QtGui.QApplication.translate("MainWindow", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.go_push_button.setText(QtGui.QApplication.translate("MainWindow", "Go", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.top_tab), QtGui.QApplication.translate("MainWindow", "TOP", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_4.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_4.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_4.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_4.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_4.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_4.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.kids_tab), QtGui.QApplication.translate("MainWindow", "Kids", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.adventure_tab), QtGui.QApplication.translate("MainWindow", "Adventure", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.education_tab), QtGui.QApplication.translate("MainWindow", "Education", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_5.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_5.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_5.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_5.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_5.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_5.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.diy_tab), QtGui.QApplication.translate("MainWindow", "DIY", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_6.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_6.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_6.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_6.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_6.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_6.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.romance_tab), QtGui.QApplication.translate("MainWindow", "Romance", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_7.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_7.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_7.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_7.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_7.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_7.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.comedy_tab), QtGui.QApplication.translate("MainWindow", "Comedy", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_8.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_8.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_8.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_8.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_8.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_8.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fantasy_tab), QtGui.QApplication.translate("MainWindow", "Fantasy", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_9.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_9.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_9.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_9.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_9.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_9.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.biography_tab), QtGui.QApplication.translate("MainWindow", "Biography", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_10.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_10.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_10.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_10.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_10.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_10.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.history_tab), QtGui.QApplication.translate("MainWindow", "History", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_11.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_11.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_11.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_11.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_11.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_11.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.magazine_tabs), QtGui.QApplication.translate("MainWindow", "Magazine", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_12.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_12.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_12.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_12.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_12.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_12.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.religion_tabs), QtGui.QApplication.translate("MainWindow", "Religion", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_13.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_13.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_13.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_13.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_13.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_13.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sports_tab), QtGui.QApplication.translate("MainWindow", "Sports", None, QtGui.QApplication.UnicodeUTF8))
        self.search_table_widget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.search_table_widget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.search_table_widget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.search_table_widget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.search_table_widget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.search_table_widget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.close_push_button.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

