# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/Ui_UploadForm.ui'
#
# Created: Sat Nov 21 18:26:49 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 619)
        self.formLayout = QtGui.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.label)
        self.title_line_edit = QtGui.QLineEdit(Form)
        self.title_line_edit.setObjectName("title_line_edit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.title_line_edit)
        self.author_line_edit = QtGui.QLineEdit(Form)
        self.author_line_edit.setObjectName("author_line_edit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.author_line_edit)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_4)
        self.genres_combo_box = QtGui.QComboBox(Form)
        self.genres_combo_box.setObjectName("genres_combo_box")
        self.genres_combo_box.addItem("")
        self.genres_combo_box.addItem("")
        self.genres_combo_box.addItem("")
        self.genres_combo_box.addItem("")
        self.genres_combo_box.addItem("")
        self.genres_combo_box.addItem("")
        self.genres_combo_box.addItem("")
        self.genres_combo_box.addItem("")
        self.genres_combo_box.addItem("")
        self.genres_combo_box.addItem("")
        self.genres_combo_box.addItem("")
        self.genres_combo_box.addItem("")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.genres_combo_box)
        self.isbn_line_edit = QtGui.QLineEdit(Form)
        self.isbn_line_edit.setObjectName("isbn_line_edit")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.isbn_line_edit)
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_5)
        self.price_spin_box = QtGui.QSpinBox(Form)
        self.price_spin_box.setMaximum(9999)
        self.price_spin_box.setObjectName("price_spin_box")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.price_spin_box)
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_6)
        self.upload_push_button = QtGui.QPushButton(Form)
        self.upload_push_button.setObjectName("upload_push_button")
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.upload_push_button)
        self.file_location_label = QtGui.QLabel(Form)
        self.file_location_label.setWordWrap(True)
        self.file_location_label.setObjectName("file_location_label")
        self.formLayout.setWidget(13, QtGui.QFormLayout.LabelRole, self.file_location_label)
        self.summary_plain_text_edit = QtGui.QPlainTextEdit(Form)
        self.summary_plain_text_edit.setObjectName("summary_plain_text_edit")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.summary_plain_text_edit)
        self.webView = QtWebKit.QWebView(Form)
        self.webView.setMinimumSize(QtCore.QSize(200, 300))
        self.webView.setMaximumSize(QtCore.QSize(200, 300))
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.webView)
        self.pick_image_push_button = QtGui.QPushButton(Form)
        self.pick_image_push_button.setObjectName("pick_image_push_button")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.pick_image_push_button)
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.label_7)
        self.submit_push_button = QtGui.QPushButton(Form)
        self.submit_push_button.setObjectName("submit_push_button")
        self.formLayout.setWidget(16, QtGui.QFormLayout.SpanningRole, self.submit_push_button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Genres", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "ISBN #", None, QtGui.QApplication.UnicodeUTF8))
        self.genres_combo_box.setItemText(0, QtGui.QApplication.translate("Form", "Kids", None, QtGui.QApplication.UnicodeUTF8))
        self.genres_combo_box.setItemText(1, QtGui.QApplication.translate("Form", "Adventure", None, QtGui.QApplication.UnicodeUTF8))
        self.genres_combo_box.setItemText(2, QtGui.QApplication.translate("Form", "Education", None, QtGui.QApplication.UnicodeUTF8))
        self.genres_combo_box.setItemText(3, QtGui.QApplication.translate("Form", "DIY", None, QtGui.QApplication.UnicodeUTF8))
        self.genres_combo_box.setItemText(4, QtGui.QApplication.translate("Form", "Romance", None, QtGui.QApplication.UnicodeUTF8))
        self.genres_combo_box.setItemText(5, QtGui.QApplication.translate("Form", "Comedy", None, QtGui.QApplication.UnicodeUTF8))
        self.genres_combo_box.setItemText(6, QtGui.QApplication.translate("Form", "Fantasy", None, QtGui.QApplication.UnicodeUTF8))
        self.genres_combo_box.setItemText(7, QtGui.QApplication.translate("Form", "Biography", None, QtGui.QApplication.UnicodeUTF8))
        self.genres_combo_box.setItemText(8, QtGui.QApplication.translate("Form", "History", None, QtGui.QApplication.UnicodeUTF8))
        self.genres_combo_box.setItemText(9, QtGui.QApplication.translate("Form", "Magazine", None, QtGui.QApplication.UnicodeUTF8))
        self.genres_combo_box.setItemText(10, QtGui.QApplication.translate("Form", "Religion", None, QtGui.QApplication.UnicodeUTF8))
        self.genres_combo_box.setItemText(11, QtGui.QApplication.translate("Form", "Sports", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Price", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.upload_push_button.setText(QtGui.QApplication.translate("Form", "Select PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.file_location_label.setText(QtGui.QApplication.translate("Form", "File:", None, QtGui.QApplication.UnicodeUTF8))
        self.pick_image_push_button.setText(QtGui.QApplication.translate("Form", "Pick Image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Cover Img", None, QtGui.QApplication.UnicodeUTF8))
        self.submit_push_button.setText(QtGui.QApplication.translate("Form", "Submit", None, QtGui.QApplication.UnicodeUTF8))

from PySide import QtWebKit
