# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\Ui_UploadForm.ui'
#
# Created: Sat Nov 21 17:15:12 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(660, 225)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.upload_push_button = QtGui.QPushButton(Form)
        self.upload_push_button.setObjectName("upload_push_button")
        self.gridLayout.addWidget(self.upload_push_button, 5, 4, 1, 1)
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 3, 1, 1)
        self.isbn_line_edit = QtGui.QLineEdit(Form)
        self.isbn_line_edit.setObjectName("isbn_line_edit")
        self.gridLayout.addWidget(self.isbn_line_edit, 1, 4, 1, 1)
        self.author_line_edit = QtGui.QLineEdit(Form)
        self.author_line_edit.setObjectName("author_line_edit")
        self.gridLayout.addWidget(self.author_line_edit, 0, 4, 1, 1)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.price_spin_box = QtGui.QSpinBox(Form)
        self.price_spin_box.setMaximum(9999)
        self.price_spin_box.setObjectName("price_spin_box")
        self.gridLayout.addWidget(self.price_spin_box, 3, 2, 1, 1)
        self.title_line_edit = QtGui.QLineEdit(Form)
        self.title_line_edit.setObjectName("title_line_edit")
        self.gridLayout.addWidget(self.title_line_edit, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.genres_combo_box = QtGui.QComboBox(Form)
        self.genres_combo_box.setObjectName("genres_combo_box")
        self.genres_combo_box.addItem("")
        self.genres_combo_box.addItem("")
        self.genres_combo_box.addItem("")
        self.genres_combo_box.addItem("")
        self.genres_combo_box.addItem("")
        self.genres_combo_box.addItem("")
        self.genres_combo_box.addItem("")
        self.genres_combo_box.addItem("")
        self.genres_combo_box.addItem("")
        self.genres_combo_box.addItem("")
        self.genres_combo_box.addItem("")
        self.genres_combo_box.addItem("")
        self.gridLayout.addWidget(self.genres_combo_box, 1, 2, 1, 1)
        self.submit_push_button = QtGui.QPushButton(Form)
        self.submit_push_button.setObjectName("submit_push_button")
        self.gridLayout.addWidget(self.submit_push_button, 6, 4, 1, 1)
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 3, 1, 1)
        self.summary_plain_text_edit = QtGui.QPlainTextEdit(Form)
        self.summary_plain_text_edit.setObjectName("summary_plain_text_edit")
        self.gridLayout.addWidget(self.summary_plain_text_edit, 4, 2, 1, 1)
        self.cover_img_line_edit = QtGui.QLineEdit(Form)
        self.cover_img_line_edit.setObjectName("cover_img_line_edit")
        self.gridLayout.addWidget(self.cover_img_line_edit, 3, 4, 1, 1)
        self.file_location_label = QtGui.QLabel(Form)
        self.file_location_label.setWordWrap(True)
        self.file_location_label.setObjectName("file_location_label")
        self.gridLayout.addWidget(self.file_location_label, 4, 3, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.title_line_edit, self.author_line_edit)
        Form.setTabOrder(self.author_line_edit, self.isbn_line_edit)
        Form.setTabOrder(self.isbn_line_edit, self.price_spin_box)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.upload_push_button.setText(QtGui.QApplication.translate("Form", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Price", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Genres", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "ISBN #", None, QtGui.QApplication.UnicodeUTF8))
        self.genres_combo_box.setItemText(0, QtGui.QApplication.translate("Form", "Kids", None, QtGui.QApplication.UnicodeUTF8))
        self.genres_combo_box.setItemText(1, QtGui.QApplication.translate("Form", "Adventure", None, QtGui.QApplication.UnicodeUTF8))
        self.genres_combo_box.setItemText(2, QtGui.QApplication.translate("Form", "Education", None, QtGui.QApplication.UnicodeUTF8))
        self.genres_combo_box.setItemText(3, QtGui.QApplication.translate("Form", "DIY", None, QtGui.QApplication.UnicodeUTF8))
        self.genres_combo_box.setItemText(4, QtGui.QApplication.translate("Form", "Romance", None, QtGui.QApplication.UnicodeUTF8))
        self.genres_combo_box.setItemText(5, QtGui.QApplication.translate("Form", "Comedy", None, QtGui.QApplication.UnicodeUTF8))
        self.genres_combo_box.setItemText(6, QtGui.QApplication.translate("Form", "Fantasy", None, QtGui.QApplication.UnicodeUTF8))
        self.genres_combo_box.setItemText(7, QtGui.QApplication.translate("Form", "Biography", None, QtGui.QApplication.UnicodeUTF8))
        self.genres_combo_box.setItemText(8, QtGui.QApplication.translate("Form", "History", None, QtGui.QApplication.UnicodeUTF8))
        self.genres_combo_box.setItemText(9, QtGui.QApplication.translate("Form", "Magazine", None, QtGui.QApplication.UnicodeUTF8))
        self.genres_combo_box.setItemText(10, QtGui.QApplication.translate("Form", "Religion", None, QtGui.QApplication.UnicodeUTF8))
        self.genres_combo_box.setItemText(11, QtGui.QApplication.translate("Form", "Sports", None, QtGui.QApplication.UnicodeUTF8))
        self.submit_push_button.setText(QtGui.QApplication.translate("Form", "Submit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Cover Img", None, QtGui.QApplication.UnicodeUTF8))
        self.file_location_label.setText(QtGui.QApplication.translate("Form", "File:", None, QtGui.QApplication.UnicodeUTF8))

